[
  "Goku",
  "Naruto Uzumaki",
  "Monkey D. Luffy",
  "Levi Ackerman",
  "Light Yagami",
  "Saitama",
  "Roronoa Zoro",
  "Edward Elric",
  "Kakashi Hatake",
  "Killua Zoldyck",
  "Spike Spiegel",
  "Tanjiro Kamado",
  "Eren Yeager",
  "Ken Kaneki",
  "Ichigo Kurosaki",
  "Vegeta",
  "L Lawliet",
  "Satoru Gojo",
  "Yuji Itadori",
  "Nezuko Kamado",
  "Izuku Midoriya",
  "Katsuki Bakugo",
  "Shoto Todoroki",
  "Sosuke Aizen",
  "Madara Uchiha",
  "Itachi Uchiha",
  "Sasuke Uchiha",
  "Mikasa Ackerman",
  "Armin Arlert",
  "Asuka Langley Soryu",
  "Shinji Ikari",
  "Rei Ayanami",
  "Motoko Kusanagi",
  "Vash the Stampede",
  "Guts",
  "Griffith",
  "Yusuke Urameshi",
  "Hiei",
  "Kurama",
  "Gon Freecss",
  "Hisoka Morow",
  "Chollo Lucilfer",
  "Roy Mustang",
  "Alphonse Elric",
  "Sesshomaru",
  "Inuyasha",
  "Kagome Higurashi",
  "Jotaro Kujo",
  "Dio Brando",
  "Giorno Giovanna",
  "Joseph Joestar",
  "Ryumen Sukuna",
  "Megumi Fushiguro",
  "Nobara Kugisaki",
  "Kento Nanami",
  "Yuta Okkotsu",
  "Suguru Geto",
  "Tanzaro Kamado",
  "Zenitsu Agatsuma",
  "Inosuke Hashibira",
  "Giyu Tomioka",
  "Shinobu Kocho",
  "Kyojuro Rengoku",
  "Akaza",
  "Muzan Kibutsuji",
  "Rimuru Tempest",
  "Ainz Ooal Gown",
  "Subaru Natsuki",
  "Emilia",
  "Rem",
  "Kazuma Satou",
  "Aqua",
  "Megumin",
  "Darkness",
  "Meliodas",
  "Ban",
  "King",
  "Escanor",
  "Tatsumaki",
  "Genos",
  "Garou",
  "Mob (Shigeo Kageyama)",
  "Reigen Arataka",
  "Denji",
  "Power",
  "Aki Hayakawa",
  "Makima",
  "Thorfinn",
  "Askeladd",
  "Canute",
  "Lucy Heartfilia",
  "Natsu Dragneel",
  "Erza Scarlet",
  "Gray Fullbuster",
  "Shikamaru Nara",
  "Hinata Hyuga",
  "Jiraiya",
  "Tsunade",
  "Orochimaru",
  "All Might"
]